spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;IGNORECASE=TRUE
  redis:
    host: localhost
  metrics:
    export:
      redis:
        prefix: metrics.${spring.application.name:application}
        key: keys.metrics.demo
logging.level.org.springframework.web: INFO
logging.level.org.springframework.web.servlet: ERROR
logging.level.hello: DEBUG
